ALTER TABLE NOTIFICATION
DROP COLUMN TYPE;

DROP TYPE NOTIFICATION_TYPE;

CREATE TYPE NOTIFICATION_TYPE AS ENUM (
	'FOLLOW', 'REKWEEK', 'LIKE', 'REPLY', 'MENTION'
);

ALTER TABLE NOTIFICATION
ADD COLUMN TYPE NOTIFICATION_TYPE NOT NULL;